Project: Tic-Tac-Toe game
hemant-soni-vst-au4/tic-tac-toe pull request #4
Opened 2020-04-30 15:26 UTC by hemant-soni-vst-au4

## Project: Tic-Tac-Toe game
- Readme file with game instruction
-  Class Game and different method used defined

2020-04-30 20:30 UTC, mosesogwo requested changes
**Hi @hemant-soni-vst-au4, please complete the previous milestone first so you can provide correct information in the README :exclamation:**
- See my comments on your README
- Do you really need to explain each method in the README? Your code itself and commit messages should sufficiently describe what is happening in the project.

### Status: Changes requested.

2020-04-30 20:30 UTC, mosesogwo commented on README.md
> +Our main `Game` class will be defined here with all the data and logic required to play a game of tic tac toe via instances of `Game`.
Are these referring to two different files?

2020-04-30 20:30 UTC, mosesogwo commented on README.md
> +
This information will change since Game class will not be residing in main.rb

2020-05-06 23:25 UTC, uryelah commented
Hello **Hemant Soni**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job with the Readme! It's very succinct.

---------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-07 05:16 UTC, merged