Testing Tic-toc-toe with Rspec
hemant-soni-vst-au4/tic-tac-toe pull request #5
Opened 2020-05-08 16:24 UTC by hemant-soni-vst-au4

## Testing Tic-toc-toe with Rspec
- input_to_index
- turn_count
- current_player
- position_taken?
- valid_move?
- full?
- over?

2020-05-09 09:26 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @hemant-soni-vst-au4 :wave: 
The test you added for the board are well organized :clap: an awesome job. But there are some issues that are blocking me to approve this right now. Let's get to them.
___
### :spades: Mandatory Changes :spades: 
___
1. Your readme does not contain any info related to tests. Please add some informative info in there.
2. You have added a test file for the main, but I cannot see any test cases. So please add some.
3. I cannot see any negative test cases in your board_spec. For example, when the valid_mode? should return false?, full? should return false and so on..
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-09 09:26 UTC, shshamim63 commented on spec/board_spec.rb
> +require './lib/board.rb'
[Optional]
When you need to require a file it is best practice to use `require_relative`.

2020-05-09 09:26 UTC, shshamim63 commented on spec/main_spec.rb
> +require './bin/main.rb'
[Optional]
Use require_relative.

2020-05-09 09:26 UTC, shshamim63 commented on spec/main_spec.rb
> +end
I can not see any test cases. Where are the test cases? Well, I checked your main.rb and the class User seems to contain tightly coupled methods. Check out this [article](https://www.codewithjason.com/test-ruby-methods-involve-puts-gets/), and let's find some cases from there that you can add in here.

2020-05-11 19:38 UTC, suretrust approved these changes
Hi @hemant-soni-vst-au4, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged. 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-05-11 19:48 UTC, merged